### ISSUE TITLE
next_max_id and min_id are deprecated for InstagramApi.tag('tag').recent_media

### ISSUE THREAD

**Issue by max-si-m** [agilie/instagram_api_gem#2]
When I try to use: `InstagramApi.tag('some_tag').recent_media`
I got an error: 

```
{"next_max_tag_id"=>
  "AQDPiODcMSv9ojCiCt9vrMDDicxZMDHRYBfWGGL879cjfFGa-9v96QBsnhptIbf8xoszFJVBNUyXqm7lG2kNZBtJBWB6cbAkOx1G1Y5iPzccUMjVBleFmLUtOA9jTh2Pquk",
 "next_max_id"=>
  "AQDPiODcMSv9ojCiCt9vrMDDicxZMDHRYBfWGGL879cjfFGa-9v96QBsnhptIbf8xoszFJVBNUyXqm7lG2kNZBtJBWB6cbAkOx1G1Y5iPzccUMjVBleFmLUtOA9jTh2Pquk",
 "next_url"=>
  ".....",
 "next_min_id"=>
  "AQDkVV8r9oGpa-XeDjrcSOvL6GLUYhNYuUEVGJETZHCx3FWZlHkKcLxoZzRg0hxpvUGQYlKaQ5_ydJBO3rYEW1oxsjmI5tEcAiG2qrRy_pe5i2jWMr00iPnEn0hMyRuaFbg",
 "min_tag_id"=>
  "AQDkVV8r9oGpa-XeDjrcSOvL6GLUYhNYuUEVGJETZHCx3FWZlHkKcLxoZzRg0hxpvUGQYlKaQ5_ydJBO3rYEW1oxsjmI5tEcAiG2qrRy_pe5i2jWMr00iPnEn0hMyRuaFbg",
 "deprecation_warning"=>
  "next_max_id and min_id are deprecated for this endpoint; use min_tag_id and max_tag_id instead"}
```

**Comment by SergeyMell** [comment]
@max-si-m, it's not an error but just `deprecation warning` to warn you against using params that can become not supported in future. You can get some more information regarding this here
https://stackoverflow.com/questions/33820651/no-pagination-information-using-instagram-api
https://stackoverflow.com/questions/34805039/instagram-pagination-deprecation-warning-in-response-when-calling-tag-search-api
However, this issue is not connected to the gem workflow, so I suppose to close it if you don't mind.
